Supa base
Alec8888/CEN3031group15 pull request #21
Opened 2023-11-21 21:46 UTC by Daniel-Eprog

Added reserved pick up, registration into database, and donator contact card on pantry page

2023-11-21 23:23 UTC, Alec8888 requested changes
@Daniel-Eprog I think on when you click reserve, the dialog opens and it should ask something like "Are you sure you want to reserve this donation?". Then there would be two buttons, one to cancel - which just closes the dialog. Another button to confirm registration. So just need to move a few things around and should be good.

2023-11-21 23:23 UTC, Alec8888 commented on Client/src/pages/pantry.vue
> +          <q-card-section v-for="(user, index) in selectedOrganization" :key="index">
@Daniel-Eprog Do we need the v-for? Are we displaying the email and phone for multiple organizations in one card? If not, then can remove the v-for and put email and phone in separate q-sections.

2023-11-22 00:12 UTC, Daniel-Eprog commented
> @Daniel-Eprog I think on when you click reserve, the dialog opens and it should ask something like "Are you sure you want to reserve this donation?". Then there would be two buttons, one to cancel - which just closes the dialog. Another button to confirm registration. So just need to move a few things around and should be good.

So for this one I removed the verification since we are adding the option to unreserve it anyway. When you click the reserve function there is an inline function call that passes parameters to the clickReserve call. This includes items that are part of the card, but then the second card pops up and asks for a confirmation, but because its a new card the parameters from the reserve fall out of scope and you lose access to it. I tried passing the parameters through to the next card, but couldn't figure it out. So I put the temporary hot fix, which will just reserve it immediately once reserved is clicked and give a confirmation.

2023-11-22 00:48 UTC, Alec8888 approved these changes

2023-11-22 00:51 UTC, merged